# Lesson 2.5: Wrapping things up?

So far, we have two types of data: `Exn` objects and everything else. And we do have a `bind` operation that works with our values. So far it works with our exception quasi-monad, but we don't have a true monad since we don't have actual monadic types, monadic variables, or anything fancy like that.

For our exceptions, it seems fine, but it won't work for more complex monads like the state or continuation monads. After all, the essence of a monad is that it wraps stuff and operates on wrap data. No wrapping means no monads. It's like buying a bowl at Chipotle with a tortilla on the side and calling it a burrito.

(Protip: If you're deciding what to order at Chiptole, you actually get more food in a bowl than in a burrito. So maybe wrapping food isn't all that it's cracked up to be?)

Let's create a class called `Value` that's nothing more except for a wrapper for our regular values:

```javascript
class Value {
  constructor(x) {
    this.x = x;
  }
}
```

And to create a class, we have a wrapper function, which, if you recall, we call `ret`:

```javascript
function ret(x) {
  return new Value(x);
}
```

And we can rewrite our `bind` function to incorporate this new `Value` type:

```javascript
function bind(m, func) {
  if (m instanceof Exn) {
    return m;
  } else if (m instanceof Value) {
    return func(m.x);
  }
}
```

Notice how `func` is a function that takes in the underlying value `m.x`, not `m` itself.

Likewise we will need to change `tryWith` in order to deal `Value` objects:

```javascript
function tryWith(m, func) {
  if (m instanceof Exn) {
    return func(m.message);
  } else if (m instanceof Value) {
    return  m;
  }
}
```

Notice how, in a way, `bind` and `tryWith` are mirror images of each other. `bind` calls `func` if the argument `m` has type `Value`, while `tryWith` does the same if `m` has type `Exn`.

In addition, we can keep the `raise` function the same, letting it return an `Exn`.

`Exn` and `Value` both function as wrappers: `Exn` for its `message` property, and `Value` for whatever `x` is storing? They're the tortillas for the burrito filling - in other words, the union of `Exn` and `Value` form the _monadic type_ used in our monad!

**Problem 1.5.0:** Now that we have our monad, what can we do with it? Let's do division!

As before, we need to write a `tryDivide` function that throws an exception if it's about to divide by zero. But this time, we need to use our monad. So `tryDivide` needs to either throw a `Exn` upon encountering `y === 0`, or it needs to return a `Value`. Let the exception message be `"division by zero!"`.

```problem
///// CODE
// The Exception monad 
class Exn {
  constructor(msg) {
    this.message = msg;
  }
}

class Value {
  constructor(x) {
    this.x = x;
  }
}

function ret(x) {
  return new Value(x);
}

function bind(m, func) {
  if (m instanceof Exn) {
    return m;
  } else if (m instanceof Value) {
    return func(m.x);
  }
}

function raise(msg) {
  return new Exn(msg);
}

function tryWith(m, func) {
  if (m instanceof Exn) {
    return func(m.message);
  } else if (m instanceof Value) {
    return  m;
  }
}

// Now to use our monad...
function tryDivide(x, y) {
  // TODO: Your code here
  // Note: You must use ret in this function
}

///// SOLUTION
class Exn {
  constructor(msg) { this.message = msg; }
}

class Value {
  constructor(x) { this.x = x; }
}

function ret(x) {
  return new Value(x);
}

function bind(m, func) {
  if (m instanceof Exn) return m;
  else if (m instanceof Value) return func(m.x);
}

function raise(msg) {
  return new Exn(msg);
}

function tryWith(m, func) {
  if (m instanceof Exn) return func(m.message);
  else if (m instanceof Value) return  m;
}

function tryDivide(x, y) {
  if (y === 0) {
    return raise("division by zero!");
  } else {
    return ret(x / y);
  }
}

///// TESTS
tryDivide(2, 1).constructor.name ==> "Value"
tryDivide(2, 0).constructor.name ==> "Exn"
tryDivide(2, 1).x ==> 2
tryDivide(2, 0).message ==> "division by zero!"
tryWith(tryDivide(2, 1), msg => ret(msg)).x ==> 2
tryWith(tryDivide(2, 0), msg => ret(msg)).x ==> "division by zero!"

///// LANGUAGE
JavaScript
```

**Problem 1.5.1:** So far, our tests have all passed the identity function into `tryWith`. In other words, if our exception has a message like `"division by zero!"`, then `tryWith` will return `"division by zero!"`. But what if we want to do more with it?

Write an `addExclamation` that adds an extra exclamation point to the end of the error message (similar to what some of the functions you wrote in Course 1 did). This `addExclamation` function will be passed into `tryWith` in our tests. The most important thing to know is that it must return a `Value` - no returning strings please!

```problem
///// CODE
// The Exception monad 
class Exn {
  constructor(msg) {
    this.message = msg;
  }
}

class Value {
  constructor(x) {
    this.x = x;
  }
}

function ret(x) {
  return new Value(x);
}

function bind(m, func) {
  if (m instanceof Exn) {
    return m;
  } else if (m instanceof Value) {
    return func(m.x);
  }
}

function raise(msg) {
  return new Exn(msg);
}

function tryWith(m, func) {
  if (m instanceof Exn) {
    return func(m.message);
  } else if (m instanceof Value) {
    return  m;
  }
}

// Now to use our monad...
function tryDivide(x, y) {
  // TODO: Copy-passte your code from above
}

// Our new func
function addExclamation(msg) {
  // TODO: Your code here
  // Note: You must use ret in this function
}

///// SOLUTION
class Exn {
  constructor(msg) { this.message = msg; }
}

class Value {
  constructor(x) { this.x = x; }
}

function ret(x) {
  return new Value(x);
}

function bind(m, func) {
  if (m instanceof Exn) return m;
  else if (m instanceof Value) return func(m.x);
}

function raise(msg) {
  return new Exn(msg);
}

function tryWith(m, func) {
  if (m instanceof Exn) return func(m.message);
  else if (m instanceof Value) return  m;
}

function tryDivide(x, y) {
  if (y === 0) {
    return raise("division by zero!");
  } else {
    return ret(x / y);
  }
}

function addExclamation(msg) {
  return ret(msg + "!");
}

///// TESTS
typeof tryWith(tryDivide(2, 0), addExclamation) ==>  "object"
tryWith(tryDivide(2, 1), addExclamation).constructor.name ==> "Value"
tryWith(tryDivide(2, 0), addExclamation).constructor.name ==> "Value"
tryWith(tryDivide(2, 1), addExclamation).x ==> 2
tryWith(tryDivide(2, 0), addExclamation).x ==> "division by zero!!"

///// LANGUAGE
JavaScript
```

**Problem 1.5.2:** So far we haven't used `bind` in this lesson. Recall that `bind` is what we ended up with when we modified `let` bindings to work with exceptions. So you can use `bind` to bind (ha ha!) monadic values and pass their data to functions.

Write `tryAdd` that takes in four arguments. It calls `tryDivide` on the first two arguments, then calls `tryDivide` on the last two arguments, then sums them together. To do this, you need to use `bind` in order to bind the results of `tryDivide` to variables before you add them together. Remember that `tryAdd` needs to return a `Value`, not a regular number.

```problem
///// CODE
// The Exception monad 
class Exn {
  constructor(msg) {
    this.message = msg;
  }
}

class Value {
  constructor(x) {
    this.x = x;
  }
}

function ret(x) {
  return new Value(x);
}

function bind(m, func) {
  if (m instanceof Exn) {
    return m;
  } else if (m instanceof Value) {
    return func(m.x);
  }
}

function raise(msg) {
  return new Exn(msg);
}

function tryWith(m, func) {
  if (m instanceof Exn) {
    return func(m.message);
  } else if (m instanceof Value) {
    return  m;
  }
}

// Now to use our monad...
function tryDivide(x, y) {
  // TODO: Copy-passte your code from above
}

function tryAdd(x1, y1, x2, y2) {
  // TODO: Your code here
  // Note: You must use ret and bind
}

///// SOLUTION
class Exn {
  constructor(msg) { this.message = msg; }
}

class Value {
  constructor(x) { this.x = x; }
}

function ret(x) {
  return new Value(x);
}

function bind(m, func) {
  if (m instanceof Exn) return m;
  else if (m instanceof Value) return func(m.x);
}

function raise(msg) {
  return new Exn(msg);
}

function tryWith(m, func) {
  if (m instanceof Exn) return func(m.message);
  else if (m instanceof Value) return  m;
}

function tryDivide(x, y) {
  if (y === 0) {
    return raise("division by zero!");
  } else {
    return ret(x / y);
  }
}

function tryAdd(x1, y1, x2, y2) {
  return bind(tryDivide(x1, y1), q1 => {
      return bind(tryDivide(x2, y2), q2 => {
        return ret(q1 + q2);
      }
    )}
  );
}

///// TESTS
tryAdd(2, 1, 9, 3).constructor.name ==> "Value"
tryAdd(2, 0, 9, 3).constructor.name ==> "Exn"
tryAdd(2, 1, 9, 0).constructor.name ==> "Exn"
tryWith(tryAdd(2, 1, 9, 3), msg => ret(msg)).x ==> 5
tryWith(tryAdd(2, 0, 9, 3), msg => ret(msg)).x ==> "division by zero!"
tryWith(tryAdd(2, 1, 9, 0), msg => ret(msg)).x ==> "division by zero!"

///// LANGUAGE
JavaScript
```

**Problem 1.5.3:** Eventually we want to escape from the Exception monad (or any monad really). This is done using the `run` operation, which takes in a monad, runs it, and returns its value to pure function land.

Part of `run` has already been written - what happens if an uncaught `Exn` is passed in. Admittedly, there's no single way to deal with this case, so for now we will return `undefined` (since that's often what happens with bad JavaScript code). Other possibilities include throwing a JavaScript exception (instead of our homegrown exceptions), returning `null`, or even just returning the `message`.

Your job is to implement the other half: what happens if a `Value` is passed in.

```problem
///// CODE
// The Exception monad 
class Exn {
  constructor(msg) {
    this.message = msg;
  }
}

class Value {
  constructor(x) {
    this.x = x;
  }
}

function ret(x) {
  return new Value(x);
}

function bind(m, func) {
  if (m instanceof Exn) {
    return m;
  } else if (m instanceof Value) {
    return func(m.x);
  }
}

function raise(msg) {
  return new Exn(msg);
}

function tryWith(m, func) {
  if (m instanceof Exn) {
    return func(m.message);
  } else if (m instanceof Value) {
    return  m;
  }
}

// Now for the final piece of the puzzle:
function run(m) {
  if (m instanceof Exn) {
    return undefined;
  } else if (m instanceof Value) {
    // TODO: Your code here
  }
}

///// SOLUTION
class Exn {
  constructor(msg) { this.message = msg; }
}

class Value {
  constructor(x) { this.x = x; }
}

function ret(x) {
  return new Value(x);
}

function bind(m, func) {
  if (m instanceof Exn) return m;
  else if (m instanceof Value) return func(m.x);
}

function raise(msg) {
  return new Exn(msg);
}

function tryWith(m, func) {
  if (m instanceof Exn) return func(m.message);
  else if (m instanceof Value) return  m;
}

function run(m) {
  if (m instanceof Exn) {
    return undefined;
  } else if (m instanceof Value) {
    return m.x;
  }
}

///// TESTS
run(ret(2)) ==> 2
run(ret(5 / 1)) ==> 5
run(bind(ret(2), x => ret(x + 2))) ==> 4
run(raise("Uh oh")) ==> "undefined"
run(tryWith(raise("Uh oh"), msg => ret(msg))) ==> "Uh oh"

///// LANGUAGE
JavaScript
```
