# Lesson 1.3: Homegrown Exceptions Pt. 2

In the previous lesson, you probably made a `raise` function that looks like this:

```javascript
function raise() {
  return "Fail!"
}
```

And you probably made a `tryWith` function that looks like this:

```javascript
function tryWith(result) {
  if (result === "Fail!") {
    return "Error!";
  } else {
    return result;
  }
}
```

It's clear that this is not exactly the most sophisticated of implementations. Some might even call it a hack! The downsides of this approach are obvious. For starters, lots of things, not just our `raise` function, return `"Fail!"`, so we might catch an excetion where none actually existed.

Instead of using strings or `null` values or whatever, what if we had a custom object for exceptions? Good thing JavaScript has one: the `Error` object. Now we can change our `raise` method to look like this:

```javascript
function raise(message) {
  return new Error(message);
}
```

Then on the `tryWith` side of things, we can write:

```javascript
function tryWith(result) {
  // We use instanceof to determine if the result is an Error object
  if (result instanceof Error) {
    return "Error";
  } else {
    return result;
  }
}
```

**Problem 1.3.0:** Use this new kind of exception (with the `Error` class) in the `tryDivide` method.

''''problem
function raise(message) {
  return new Error(message);
}

function tryWith(result) {
  if (result instanceof Error) return "Error";
  else return result;
}

function tryDivide(x, y) {
  // Your code here
}
''''

**Problem 1.3.1:** In the `raise` method, we pass in a `message` argument in order to customize what error messages we want to get. But right now `tryWith` always returns `"Error"` if it catches an exception. Rewrite `tryWith` in order to return the `message` we passed in.

''''problem
function raise(message) {
  return new Error(message);
}

function tryWith(result) {
  // Your code here
}
''''

**Problem 1.3.2:** Wait, aren't we supposed to create our own exceptions from scratch? Why the heck are we using an in-built JS object like `Error` then? Write a custom `Exn` class that behaves similarly to how `Error` behaves, and rewrite `raise`, `tryWith`, and `tryDivide` to use `Exn` objects.

''''problem
class Exn {
  // Your code here
}

function raise(message) {
  // Your code here
}

function tryWith(result) {
  // Your code here
}

function tryDivide(x, y) {
  // Your code here
}
''''
