# Lessons 1.2: Functional Exceptions Part 1

So let’s imagine we’re starting from functional JavaScript and we want to add our own exceptions in. We know that they need two parts: a way to throw exceptions and a way to catch them. Let’s consider an operation `raise`,named differently in order to distinguish from JS's built-in `throw` keyword. Since people often talk about "raising" an exception as a synonym for throwing them, it's a decent name.

What does `raise` do? For now, let's make `raise` do absolutely nothing:

```javascript
function throw() {}
```

What? How does that make sense? Well, the key idea is that we call `raise` whenever we exit a function early, before we reached its return statement. That’s cool; if you see a function like this:

```javascript
function tryDivide(x, y) {
    if (y === 0) {
        raise();
    } else {
        return x / y;
    }
}
```

You immediately know "Hey, if the divisor equals 0, that means we call `raise` and exit the function early! Hooray for no division by zero!"
